package com.thecoffeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.*;
import java.util.Date;

/**
 * Atposition generated by hbm2java
 */
@Entity
@Table(name = "atposition", catalog = "theshopcoffee")
public class Atposition implements java.io.Serializable {
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "employeeid", column = @Column(name = "EMPLOYEEID", nullable = false, length = 7)),
			@AttributeOverride(name = "positionid", column = @Column(name = "POSITIONID", nullable = false)) })
	private AtpositionId id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEEID", nullable = false, insertable = false, updatable = false)
	private Employee employee;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POSITIONID", nullable = false, insertable = false, updatable = false)
	private Position position;

	@Temporal(TemporalType.DATE)
	@Column(name = "STARTDATE", length = 10)
	private Date startdate;

	@Temporal(TemporalType.DATE)
	@Column(name = "ENDDATE", length = 10)
	private Date enddate;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	private Date updateat;

	@Column(name = "ISDELETE")
	private Boolean isdelete;

	public Atposition() {
	}

	public Atposition(AtpositionId id, Date startdate, Date enddate, Boolean isdelete) {
		this.id = id;
		this.startdate = startdate;
		this.enddate = enddate;
		this.isdelete = isdelete;
	}

	public Atposition(AtpositionId id, Employee employee, Position position) {
		this.id = id;
		this.employee = employee;
		this.position = position;
	}

	public Atposition(AtpositionId id, Employee employee, Position position, Date startdate, Date enddate,
			Date updateat, Boolean isdelete) {
		this.id = id;
		this.employee = employee;
		this.position = position;
		this.startdate = startdate;
		this.enddate = enddate;
		this.updateat = updateat;
		this.isdelete = isdelete;
	}


	public AtpositionId getId() {
		return this.id;
	}

	public void setId(AtpositionId id) {
		this.id = id;
	}


	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}


	public Position getPosition() {
		return this.position;
	}

	public void setPosition(Position position) {
		this.position = position;
	}


	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}


	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}


	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}


	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

	@Override
	public String toString() {
		return "Atposition{" +
				"id=" + id +
				", employee=" + employee +
				", position=" + position +
				", startdate=" + startdate +
				", enddate=" + enddate +
				", updateat=" + updateat +
				", isdelete=" + isdelete +
				'}';
	}
}
