package com.thecoffeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Bill generated by hbm2java
 */
@Entity
@Table(name = "bill", catalog = "theshopcoffee")
public class Bill implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "BILLID", unique = true, nullable = false)
	private Integer billid;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BILLSTATUSID")
	private Billstatus billstatus;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMERID")
	private Customer customer;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DINNERTABLEID")
	private Dinnertable dinnertable;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEEID")
	private Employee employee;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VOUCHERID")
	private Voucher voucher;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "STARTDATETIME", length = 19)
	private Date startdatetime;

	@Temporal(TemporalType.DATE)
	@Column(name = "ENDDATE", length = 10)
	private Date enddate;

	@Column(name = "NOTICE")
	private String notice;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	private Date updateat;

	@Column(name = "ISDELETE")
	private Boolean isdelete;

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "bill")
	private Set<Billdetail> billdetails = new HashSet<Billdetail>(0);

	public Bill() {
	}

	public Bill(Integer billid) {
		this.billid = billid;
	}

	public Bill(Integer billid, Billstatus billstatus, Customer customer, Dinnertable dinnertable, Employee employee,
			Voucher voucher, Date startdatetime, Date enddate, String notice, Date updateat, Boolean isdelete,
			Set<Billdetail> billdetails) {
		this.billid = billid;
		this.billstatus = billstatus;
		this.customer = customer;
		this.dinnertable = dinnertable;
		this.employee = employee;
		this.voucher = voucher;
		this.startdatetime = startdatetime;
		this.enddate = enddate;
		this.notice = notice;
		this.updateat = updateat;
		this.isdelete = isdelete;
		this.billdetails = billdetails;
	}


	public Integer getBillid() {
		return this.billid;
	}

	public void setBillid(Integer billid) {
		this.billid = billid;
	}


	public Billstatus getBillstatus() {
		return this.billstatus;
	}

	public void setBillstatus(Billstatus billstatus) {
		this.billstatus = billstatus;
	}


	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}


	public Dinnertable getDinnertable() {
		return this.dinnertable;
	}

	public void setDinnertable(Dinnertable dinnertable) {
		this.dinnertable = dinnertable;
	}


	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}


	public Voucher getVoucher() {
		return this.voucher;
	}

	public void setVoucher(Voucher voucher) {
		this.voucher = voucher;
	}


	public Date getStartdatetime() {
		return this.startdatetime;
	}

	public void setStartdatetime(Date startdatetime) {
		this.startdatetime = startdatetime;
	}


	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}


	public String getNotice() {
		return this.notice;
	}

	public void setNotice(String notice) {
		this.notice = notice;
	}


	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}


	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}


	public Set<Billdetail> getBilldetails() {
		return this.billdetails;
	}

	public void setBilldetails(Set<Billdetail> billdetails) {
		this.billdetails = billdetails;
	}

}
