package com.thecoffeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.*;
import java.util.Date;

/**
 * Billdetail generated by hbm2java
 */
@Entity
@Table(name = "billdetail", catalog = "theshopcoffee")
public class Billdetail implements java.io.Serializable {
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "productid", column = @Column(name = "PRODUCTID", nullable = false, length = 7)),
			@AttributeOverride(name = "billid", column = @Column(name = "BILLID", nullable = false)) })
	private BilldetailId id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BILLID", nullable = false, insertable = false, updatable = false)
	private Bill bill;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCTID", nullable = false, insertable = false, updatable = false)
	private Product product;

	@Column(name = "QUANTITY")
	private Integer quantity;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	private Date updateat;

	@Column(name = "ISDELETE")
	private Boolean isdelete;

	public Billdetail() {
	}

	public Billdetail(BilldetailId id, Bill bill, Product product) {
		this.id = id;
		this.bill = bill;
		this.product = product;
	}

	public Billdetail(BilldetailId id, Bill bill, Product product, Integer quantity, Date updateat, Boolean isdelete) {
		this.id = id;
		this.bill = bill;
		this.product = product;
		this.quantity = quantity;
		this.updateat = updateat;
		this.isdelete = isdelete;
	}


	public BilldetailId getId() {
		return this.id;
	}

	public void setId(BilldetailId id) {
		this.id = id;
	}


	public Bill getBill() {
		return this.bill;
	}

	public void setBill(Bill bill) {
		this.bill = bill;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

}
