package com.thecoffeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.*;
import java.util.Date;

/**
 * Booktable generated by hbm2java
 */
@Entity
@Table(name = "booktable", catalog = "theshopcoffee")
public class Booktable implements java.io.Serializable {
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "customerid", column = @Column(name = "CUSTOMERID", nullable = false)),
			@AttributeOverride(name = "dinnertableid", column = @Column(name = "DINNERTABLEID", nullable = false)),
			@AttributeOverride(name = "employeeid", column = @Column(name = "EMPLOYEEID", nullable = false, length = 7)) })
	private BooktableId id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMERID", nullable = false, insertable = false, updatable = false)
	private Customer customer;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DINNERTABLEID", nullable = false, insertable = false, updatable = false)
	private Dinnertable dinnertable;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEEID", nullable = false, insertable = false, updatable = false)
	private Employee employee;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "STARTDATETIME", length = 19)
	private Date startdatetime;

	@Column(name = "STATUS")
	private Boolean status;

	@Column(name = "COUNTPEOPLE")
	private Integer countpeople;

	@Column(name = "NOTICE")
	private String notice;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	private Date updateat;

	@Column(name = "ISDELETE")
	private Boolean isdelete;

	public Booktable() {
	}

	public Booktable(BooktableId id, Customer customer, Dinnertable dinnertable, Employee employee) {
		this.id = id;
		this.customer = customer;
		this.dinnertable = dinnertable;
		this.employee = employee;
	}

	public Booktable(BooktableId id, Customer customer, Dinnertable dinnertable, Employee employee, Date startdatetime,
			Boolean status, Integer countpeople, String notice, Date updateat, Boolean isdelete) {
		this.id = id;
		this.customer = customer;
		this.dinnertable = dinnertable;
		this.employee = employee;
		this.startdatetime = startdatetime;
		this.status = status;
		this.countpeople = countpeople;
		this.notice = notice;
		this.updateat = updateat;
		this.isdelete = isdelete;
	}


	public BooktableId getId() {
		return this.id;
	}

	public void setId(BooktableId id) {
		this.id = id;
	}


	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}


	public Dinnertable getDinnertable() {
		return this.dinnertable;
	}

	public void setDinnertable(Dinnertable dinnertable) {
		this.dinnertable = dinnertable;
	}


	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}


	public Date getStartdatetime() {
		return this.startdatetime;
	}

	public void setStartdatetime(Date startdatetime) {
		this.startdatetime = startdatetime;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public Integer getCountpeople() {
		return this.countpeople;
	}

	public void setCountpeople(Integer countpeople) {
		this.countpeople = countpeople;
	}

	public String getNotice() {
		return this.notice;
	}

	public void setNotice(String notice) {
		this.notice = notice;
	}

	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

}
