package com.thecoffeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Categoryproduct generated by hbm2java
 */
@Entity
@Table(name = "categoryproduct", catalog = "theshopcoffee")
public class Categoryproduct implements java.io.Serializable {
	@Id
	@Column(name = "CATEGORYPRODUCTID", unique = true, nullable = false, length = 7)
	private String categoryproductid;

	@Column(name = "NAME")
	private String name;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	private Date updateat;

	@Column(name = "ISDELETE")
	private Boolean isdelete;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoryproduct")
	private Set<Product> products = new HashSet<Product>(0);

	public Categoryproduct() {
	}

	public Categoryproduct(String categoryproductid) {
		this.categoryproductid = categoryproductid;
	}

	public Categoryproduct(String categoryproductid, String name, Boolean isdelete, Set<Product> products) {
		this.categoryproductid = categoryproductid;
		this.name = name;
		this.isdelete = isdelete;
		this.products = products;
	}


	public String getCategoryproductid() {
		return this.categoryproductid;
	}

	public void setCategoryproductid(String categoryproductid) {
		this.categoryproductid = categoryproductid;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
