package com.thecoffeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "theshopcoffee")
public class Customer implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CUSTOMERID", unique = true, nullable = false)
	private int customerid;

	@Column(name = "NAME")
	private String name;

	@Column(name = "ADDRESS")
	private String address;

	@Column(name = "PHONE", precision = 10, scale = 0)
	private Integer phone;

	@Column(name = "PASSWORD")
	private String password;

	@Column(name = "ISDELETE")
	private Boolean isdelete;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	private Set<Bill> bills = new HashSet<Bill>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	private Set<Booktable> booktables = new HashSet<Booktable>(0);

	public Customer() {
	}

	public Customer(int customerid) {
		this.customerid = customerid;
	}

	public Customer(int customerid, String name, String address, Integer phone, Boolean isdelete, Set<Bill> bills,
			Set<Booktable> booktables) {
		this.customerid = customerid;
		this.name = name;
		this.address = address;
		this.phone = phone;
		this.isdelete = isdelete;
		this.bills = bills;
		this.booktables = booktables;
	}
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getCustomerid() {
		return this.customerid;
	}

	public void setCustomerid(int customerid) {
		this.customerid = customerid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}


	public Integer getPhone() {
		return this.phone;
	}

	public void setPhone(Integer phone) {
		this.phone = phone;
	}

	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

	public Set<Bill> getBills() {
		return this.bills;
	}

	public void setBills(Set<Bill> bills) {
		this.bills = bills;
	}

	public Set<Booktable> getBooktables() {
		return this.booktables;
	}

	public void setBooktables(Set<Booktable> booktables) {
		this.booktables = booktables;
	}

	@Override
	public String toString() {
		return "Customer{" +
				"customerid=" + customerid +
				", name='" + name + '\'' +
				", address='" + address + '\'' +
				", phone=" + phone +
				", password='" + password + '\'' +
				", isdelete=" + isdelete +
				", bills=" + bills +
				", booktables=" + booktables +
				'}';
	}
}
