package com.thecoffeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Dinnertable generated by hbm2java
 */
@Entity
@Table(name = "dinnertable", catalog = "theshopcoffee")
public class Dinnertable implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "DINNERTABLEID", unique = true, nullable = false)
	private int dinnertableid;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TABLESTATUSID")
	private Tablestatus tablestatus;

	@Column(name = "NAME")
	private String name;

	@Column(name = "COUNTCHAIR")
	private Integer countchair;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	private Date updateat;

	@Column(name = "ISDELETE")
	private Boolean isdelete;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dinnertable")
	private Set<Booktable> booktables = new HashSet<Booktable>();
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dinnertable")
	private Set<Bill> bills = new HashSet<Bill>();

	public Dinnertable() {
	}

	public Dinnertable(int dinnertableid) {
		this.dinnertableid = dinnertableid;
	}

	public Dinnertable(int dinnertableid, Tablestatus tablestatus, String name, Integer countchair, Date updateat,
			Boolean isdelete, Set<Booktable> booktables, Set<Bill> bills) {
		this.dinnertableid = dinnertableid;
		this.tablestatus = tablestatus;
		this.name = name;
		this.countchair = countchair;
		this.updateat = updateat;
		this.isdelete = isdelete;
		this.booktables = booktables;
		this.bills = bills;
	}


	public int getDinnertableid() {
		return this.dinnertableid;
	}

	public void setDinnertableid(int dinnertableid) {
		this.dinnertableid = dinnertableid;
	}

	public Tablestatus getTablestatus() {
		return this.tablestatus;
	}

	public void setTablestatus(Tablestatus tablestatus) {
		this.tablestatus = tablestatus;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public Integer getCountchair() {
		return this.countchair;
	}

	public void setCountchair(Integer countchair) {
		this.countchair = countchair;
	}

	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

	public Set<Booktable> getBooktables() {
		return this.booktables;
	}

	public void setBooktables(Set<Booktable> booktables) {
		this.booktables = booktables;
	}

	public Set<Bill> getBills() {
		return this.bills;
	}

	public void setBills(Set<Bill> bills) {
		this.bills = bills;
	}

}
