package com.thecoffeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.*;
import java.util.Date;

/**
 * Exportbilldetail generated by hbm2java
 */
@Entity
@Table(name = "exportbilldetail", catalog = "theshopcoffee")
public class Exportbilldetail implements java.io.Serializable {
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "exportbillid", column = @Column(name = "EXPORTBILLID", nullable = false)),
			@AttributeOverride(name = "materialdetailid", column = @Column(name = "MATERIALDETAILID", nullable = false)) })
	private ExportbilldetailId id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXPORTBILLID", nullable = false, insertable = false, updatable = false)
	private Exportbill exportbill;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MATERIALDETAILID", nullable = false, insertable = false, updatable = false)
	private Materialdetail materialdetail;

	@Column(name = "QUANTITY")
	private Integer quantity;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	private Date updateat;

	@Column(name = "ISDELETE")
	private Boolean isdelete;

	public Exportbilldetail() {
	}

	public Exportbilldetail(ExportbilldetailId id, Exportbill exportbill, Materialdetail materialdetail) {
		this.id = id;
		this.exportbill = exportbill;
		this.materialdetail = materialdetail;
	}

	public Exportbilldetail(ExportbilldetailId id, Exportbill exportbill, Materialdetail materialdetail,
			Integer quantity, Date updateat, Boolean isdelete) {
		this.id = id;
		this.exportbill = exportbill;
		this.materialdetail = materialdetail;
		this.quantity = quantity;
		this.updateat = updateat;
		this.isdelete = isdelete;
	}


	public ExportbilldetailId getId() {
		return this.id;
	}

	public void setId(ExportbilldetailId id) {
		this.id = id;
	}


	public Exportbill getExportbill() {
		return this.exportbill;
	}

	public void setExportbill(Exportbill exportbill) {
		this.exportbill = exportbill;
	}

	public Materialdetail getMaterialdetail() {
		return this.materialdetail;
	}

	public void setMaterialdetail(Materialdetail materialdetail) {
		this.materialdetail = materialdetail;
	}


	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

}
