package com.thecoffeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Importbill generated by hbm2java
 */
@Entity
@Table(name = "importbill", catalog = "theshopcoffee")
public class Importbill implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IMPORTBILLID", unique = true, nullable = false)
	private int importbillid;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "EMPLOYEEID")
	private Employee employee;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SUPPLIERID")
	private Supplier supplier;


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	private Date updateat;

	@Column(name = "ISDELETE")
	private Boolean isdelete;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "importbill")
	private Set<Importbilldetail> importbilldetails = new HashSet<Importbilldetail>(0);

	public Importbill() {
	}

	public Importbill(int importbillid) {
		this.importbillid = importbillid;
	}

	public Importbill(int importbillid, Employee employee, Supplier supplier, Date updateat, Boolean isdelete,
			Set<Importbilldetail> importbilldetails) {
		this.importbillid = importbillid;
		this.employee = employee;
		this.supplier = supplier;
		this.updateat = updateat;
		this.isdelete = isdelete;
		this.importbilldetails = importbilldetails;
	}


	public int getImportbillid() {
		return this.importbillid;
	}

	public void setImportbillid(int importbillid) {
		this.importbillid = importbillid;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Supplier getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}


	public Set<Importbilldetail> getImportbilldetails() {
		return this.importbilldetails;
	}

	public void setImportbilldetails(Set<Importbilldetail> importbilldetails) {
		this.importbilldetails = importbilldetails;
	}

}
