package com.thecoffeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Material generated by hbm2java
 */
@Entity
@Table(name = "material", catalog = "theshopcoffee")
public class Material implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MATERIALID", unique = true, nullable = false)
	private int materialid;

	@Column(name = "NAME")
	private String name;

	@Column(name = "UNIT", length = 50)
	private String unit;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	private Date updateat;

	@Column(name = "ISDELETE")
	private Boolean isdelete;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "material")
	private Set<Materialdetail> materialdetails = new HashSet<Materialdetail>(0);

	public Material() {
	}

	public Material(int materialid) {
		this.materialid = materialid;
	}

	public Material(int materialid, String name, String unit, Date updateat, Boolean isdelete,
			Set<Materialdetail> materialdetails) {
		this.materialid = materialid;
		this.name = name;
		this.unit = unit;
		this.updateat = updateat;
		this.isdelete = isdelete;
		this.materialdetails = materialdetails;
	}


	public int getMaterialid() {
		return this.materialid;
	}

	public void setMaterialid(int materialid) {
		this.materialid = materialid;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}


	public Set<Materialdetail> getMaterialdetails() {
		return this.materialdetails;
	}

	public void setMaterialdetails(Set<Materialdetail> materialdetails) {
		this.materialdetails = materialdetails;
	}

}
