package com.thecoffeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Materialdetail generated by hbm2java
 */
@Entity
@Table(name = "materialdetail", catalog = "theshopcoffee")
public class Materialdetail implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MATERIALDETAILID", unique = true, nullable = false)
	private int materialdetailid;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MATERIALID")
	private Material material;
	@Temporal(TemporalType.DATE)

	@Column(name = "DATEOFMANUFACTURE", length = 10)
	private Date dateofmanufacture;

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPIRATIONDATE", length = 10)
	private Date expirationdate;

	@Column(name = "QUANTITY")
	private Integer quantity;

	@Column(name = "PRICE")
	private Integer price;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	private Date updateat;

	@Column(name = "ISDELETE")
	private Boolean isdelete;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materialdetail")
	private Set<Importbilldetail> importbilldetails = new HashSet<Importbilldetail>();

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materialdetail")
	private Set<Exportbilldetail> exportbilldetails = new HashSet<Exportbilldetail>();

	public Materialdetail() {
	}

	public Materialdetail(int materialdetailid) {
		this.materialdetailid = materialdetailid;
	}




	public int getMaterialdetailid() {
		return this.materialdetailid;
	}

	public void setMaterialdetailid(int materialdetailid) {
		this.materialdetailid = materialdetailid;
	}


	public Material getMaterial() {
		return this.material;
	}

	public void setMaterial(Material material) {
		this.material = material;
	}


	public Date getDateofmanufacture() {
		return this.dateofmanufacture;
	}

	public void setDateofmanufacture(Date dateofmanufacture) {
		this.dateofmanufacture = dateofmanufacture;
	}


	public Date getExpirationdate() {
		return this.expirationdate;
	}

	public void setExpirationdate(Date expirationdate) {
		this.expirationdate = expirationdate;
	}


	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}


	public Set<Importbilldetail> getImportbilldetails() {
		return this.importbilldetails;
	}

	public void setImportbilldetails(Set<Importbilldetail> importbilldetails) {
		this.importbilldetails = importbilldetails;
	}

	public Set<Exportbilldetail> getExportbilldetails() {
		return this.exportbilldetails;
	}

	public void setExportbilldetails(Set<Exportbilldetail> exportbilldetails) {
		this.exportbilldetails = exportbilldetails;
	}

}
