package com.thecoffeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Position generated by hbm2java
 */
@Entity
@Table(name = "position", catalog = "theshopcoffee")
public class Position implements java.io.Serializable {
	@Id
	@Column(name = "POSITIONID", unique = true, nullable = false)
	private String positionid;

	@Column(name = "NAME")
	private String name;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	private Date updateat;

	@Column(name = "ISDELETE")
	private Boolean isdelete;



	@ManyToMany
	@JoinTable(
			name = "atposition",
			joinColumns = @JoinColumn(name = "positionid"),
			inverseJoinColumns = @JoinColumn(name = "employeeid"))

	private Set<Employee> employees = new HashSet<Employee>(0);

	public Position() {
	}

	public Position(String positionid) {
		this.positionid = positionid;
	}

	public Position(String positionid, String name, Date updateat, Boolean isdelete, Set<Employee> atpositions) {
		this.positionid = positionid;
		this.name = name;
		this.updateat = updateat;
		this.isdelete = isdelete;
		this.employees = atpositions;
	}


	public String getPositionid() {
		return this.positionid;
	}

	public void setPositionid(String positionid) {
		this.positionid = positionid;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}


	public Set<Employee> getEmployees() {
		return employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}
}
