package com.thecoffeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "theshopcoffee")
public class Product implements java.io.Serializable {
	@Id
	@Column(name = "PRODUCTID", unique = true, nullable = false, length = 7)
	private String productid;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CATEGORYPRODUCTID")
	private Categoryproduct categoryproduct;

	@Column(name = "NAME")
	private String name;

	@Column(name = "DESCRIPTION")
	private String description;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	private Date updateat;

	@Column(name = "ISDELETE")
	private Boolean isdelete;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	private Set<Billdetail> billdetails = new HashSet<Billdetail>(0);

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "imageofproduct", catalog = "theshopcoffee", joinColumns = {
			@JoinColumn(name = "PRODUCTID", nullable = false, updatable = false) }, inverseJoinColumns = {
			@JoinColumn(name = "IMAGEID", nullable = false, updatable = false) })
	private Set<Image> images = new HashSet<Image>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	private Set<Exportbill> exportbills = new HashSet<Exportbill>();
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	private Set<Price> prices = new HashSet<Price>();

	public Product() {
	}

	public Product(String productid) {
		this.productid = productid;
	}




	public String getProductid() {
		return this.productid;
	}

	public void setProductid(String productid) {
		this.productid = productid;
	}


	public Categoryproduct getCategoryproduct() {
		return this.categoryproduct;
	}

	public void setCategoryproduct(Categoryproduct categoryproduct) {
		this.categoryproduct = categoryproduct;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}


	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

	public Set<Billdetail> getBilldetails() {
		return this.billdetails;
	}

	public void setBilldetails(Set<Billdetail> billdetails) {
		this.billdetails = billdetails;
	}

	public Set<Image> getImages() {
		return this.images;
	}

	public void setImages(Set<Image> images) {
		this.images = images;
	}

	public Set<Exportbill> getExportbills() {
		return this.exportbills;
	}

	public void setExportbills(Set<Exportbill> exportbills) {
		this.exportbills = exportbills;
	}

	public Set<Price> getPrices() {
		return this.prices;
	}

	public void setPrices(Set<Price> prices) {
		this.prices = prices;
	}


}
