package com.thecoffeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Register generated by hbm2java
 */
@Entity
@Table(name = "register", catalog = "theshopcoffee")
public class Register implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "REGISTERID", unique = true, nullable = false)
	private int registerid;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEEID")
	private Employee employee;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SCHEDULEID")
	private Schedule schedule;

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE", length = 10)
	private Date date;

	@Column(name = "RESULT")
	private int result;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	private Date updateat;

	@Column(name = "ISDELETE")
	private Boolean isdelete;

	public Register() {
	}

	public Register(int registerid) {
		this.registerid = registerid;
	}

	public Register(int registerid, Employee employee, Schedule schedule, Date date, int result, Date updateat,
			Boolean isdelete) {
		this.registerid = registerid;
		this.employee = employee;
		this.schedule = schedule;
		this.date = date;
		this.result = result;
		this.updateat = updateat;
		this.isdelete = isdelete;
	}


	public int getRegisterid() {
		return this.registerid;
	}

	public void setRegisterid(int registerid) {
		this.registerid = registerid;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Schedule getSchedule() {
		return this.schedule;
	}

	public void setSchedule(Schedule schedule) {
		this.schedule = schedule;
	}


	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public int getResult() {
		return this.result;
	}

	public void setResult(int result) {
		this.result = result;
	}

	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

}
