package com.thecoffeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Salary generated by hbm2java
 */
@Entity
@Table(name = "salary", catalog = "theshopcoffee")
public class Salary implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SALARYID", unique = true, nullable = false)
	private int salaryid;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEEID")
	private Employee employee;

	@Column(name = "SALARYONHOUR")
	private Integer salaryonhour;

	@Temporal(TemporalType.DATE)
	@Column(name = "STARTDATE", length = 10)
	private Date startdate;

	@Temporal(TemporalType.DATE)
	@Column(name = "ENDDATE", length = 10)
	private Date enddate;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	private Date updateat;

	@Column(name = "ISDELETE")
	private Boolean isdelete;
	public Salary() {
	}

	public Salary(int salaryid) {
		this.salaryid = salaryid;
	}

	public Salary(int salaryid, Employee employee, Integer salaryonhour, Date startdate, Date enddate, Date updateat,
			Boolean isdelete) {
		this.salaryid = salaryid;
		this.employee = employee;
		this.salaryonhour = salaryonhour;
		this.startdate = startdate;
		this.enddate = enddate;
		this.updateat = updateat;
		this.isdelete = isdelete;
	}


	public int getSalaryid() {
		return this.salaryid;
	}

	public void setSalaryid(int salaryid) {
		this.salaryid = salaryid;
	}


	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Integer getSalaryonhour() {
		return this.salaryonhour;
	}

	public void setSalaryonhour(Integer salaryonhour) {
		this.salaryonhour = salaryonhour;
	}


	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

}
