package com.thecoffeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "supplier", catalog = "theshopcoffee")
public class Supplier implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SUPPLIERID", unique = true, nullable = false)
	private int supplierid;


	@Column(name = "NAME")
	private String name;

	@Column(name = "ADDRESS")
	private String address;

	@Column(name = "PHONE")
	private String phone;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	private Date updateat;

	@Column(name = "ISDELETE")
	private Boolean isdelete;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	private Set<Importbill> importbills = new HashSet<Importbill>(0);

	public Supplier() {
	}

	public Supplier(int supplierid) {
		this.supplierid = supplierid;
	}

	public Supplier(int supplierid, String name, String address, String phone, Date updateat, Boolean isdelete,
			Set<Importbill> importbills) {
		this.supplierid = supplierid;
		this.name = name;
		this.address = address;
		this.phone = phone;
		this.updateat = updateat;
		this.isdelete = isdelete;
		this.importbills = importbills;
	}


	public int getSupplierid() {
		return this.supplierid;
	}

	public void setSupplierid(int supplierid) {
		this.supplierid = supplierid;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "PHONE", length = 7)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}


	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}


	public Set<Importbill> getImportbills() {
		return this.importbills;
	}

	public void setImportbills(Set<Importbill> importbills) {
		this.importbills = importbills;
	}

}
