package com.thecoffeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Tablestatus generated by hbm2java
 */
@Entity
@Table(name = "tablestatus", catalog = "theshopcoffee")
public class Tablestatus implements java.io.Serializable {
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "TABLESTATUSID", unique = true, nullable = false)
    private int tablestatusid;

    @Column(name = "NAME")
    private String name;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATEAT", length = 19)
    private Date updateat;

    @Column(name = "ISDELETE")
    private Boolean isdelete;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tablestatus")
    private Set<Dinnertable> dinnertables = new HashSet<Dinnertable>(0);

    public Tablestatus() {
    }

    public Tablestatus(int tablestatusid) {
        this.tablestatusid = tablestatusid;
    }

    public Tablestatus(int tablestatusid, String name, Date updateat, Boolean isdelete, Set<Dinnertable> dinnertables) {
        this.tablestatusid = tablestatusid;
        this.name = name;
        this.updateat = updateat;
        this.isdelete = isdelete;
        this.dinnertables = dinnertables;
    }


    public int getTablestatusid() {
        return this.tablestatusid;
    }

    public void setTablestatusid(int tablestatusid) {
        this.tablestatusid = tablestatusid;
    }


    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getUpdateat() {
        return this.updateat;
    }

    public void setUpdateat(Date updateat) {
        this.updateat = updateat;
    }

    public Boolean getIsdelete() {
        return this.isdelete;
    }

    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }


    public Set<Dinnertable> getDinnertables() {
        return this.dinnertables;
    }

    public void setDinnertables(Set<Dinnertable> dinnertables) {
        this.dinnertables = dinnertables;
    }

}
